# Use an official Node.js runtime as the base image
FROM node:14 AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker's layer caching
COPY package*.json ./

# Install dependencies (you can replace 'npm' with 'yarn' if preferred)
RUN npm install --production

# Copy the rest of the application source code
COPY . .

RUN npm run build
FROM node:14-slim

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json

EXPOSE 1337

ENV NODE_ENV=production

CMD ["node", "./dist/index.js"]